chore(webui): persist column selection to localStorage in evals view
promptfoo/promptfoo pull request #1302
Opened 2024-07-27 16:34 UTC by mldangelo

Implements localStorage persistence for selected columns

1. Open the /evals page in the browser.
2. Select or deselect some columns.
3. Refresh the page and verify that the column selection state is preserved.
5. Check the browser's localStorage to confirm the presence of the persisted data.
6. Test with different eval IDs to ensure unique storage keys are used.
7. Verify that the column visibility in the table reflects the persisted state.

In the future we can consider moving this to persist across datasets instead of columns.

2024-07-27 19:00 UTC, typpo requested changes

2024-07-27 19:00 UTC, typpo commented on src/web/nextui/src/app/eval/ResultsView.tsx
> +// Utility function to safely parse JSON
This seems like it could be named better as it only supports

2024-07-27 19:00 UTC, typpo commented on src/web/nextui/src/app/eval/ResultsView.tsx
> +    localStorage.setItem(localStorageKey, JSON.stringify(debouncedSelectedColumns));
Prefer using `./store`, which is where we store and fetch other settings.

2024-07-28 00:47 UTC, mldangelo commented on src/web/nextui/src/app/eval/ResultsView.tsx
> +  const currentEvalId = evalId || defaultEvalId || 'default';
instead of `|| 'default';` we could disable the feature. I think this only affects supabase but I am not sure.

2024-07-28 04:10 UTC, typpo commented on src/web/nextui/src/app/eval/ResultsView.tsx
> +  const promptOptions = useMemo(() => {
nit: we use `React.useMemo`, `React.useEffect` in most places elsewhere in the codebase. Let's prefer to keep the `React` namespace

2024-07-28 04:10 UTC, typpo commented on src/web/nextui/src/app/eval/ResultsView.tsx
> +  useEffect(() => {
nit: maybe move `currentColumnState` definition down here to above where it's used?

2024-07-28 04:10 UTC, typpo commented on src/web/nextui/src/app/eval/store.ts
> +      partialize: (state) => ({
Pretty sure this omits all the other properties from storage, which is not what we want.  The entire state object is stored by default.

2024-07-29 04:25 UTC, typpo approved these changes

2024-07-29 21:02 UTC, merged